package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Carbon Slate (Classic Premium Dark)
val CarbonBg = Color(0xFF121417)
val CarbonDisplayBg = Color(0xFF1E222B)
val CarbonText = Color(0xFFFFFFFF)
val CarbonTextFaded = Color(0xFF8B9FB4)
val CarbonDigit = Color(0xFF262D37)
val CarbonOnDigit = Color(0xFFF3F4F6)
val CarbonAction = Color(0xFF384351)
val CarbonOnAction = Color(0xFFE5E7EB)
val CarbonAccent = Color(0xFF00ADB5)
val CarbonOnAccent = Color(0xFFFFFFFF)

// Solar Pop (Energetic Warm Light)
val SolarBg = Color(0xFFFBF8F2)
val SolarDisplayBg = Color(0xFFFFFDF9)
val SolarText = Color(0xFF2B2824)
val SolarTextFaded = Color(0xFF8C8476)
val SolarDigit = Color(0xFFFFFFFF)
val SolarOnDigit = Color(0xFF2B2824)
val SolarAction = Color(0xFFE3DCCF)
val SolarOnAction = Color(0xFF4C453C)
val SolarAccent = Color(0xFFFF5722)
val SolarOnAccent = Color(0xFFFFFFFF)

// Retro Hacker (Neon Green Terminal)
val RetroBg = Color(0xFF050B05)
val RetroDisplayBg = Color(0xFF0B120B)
val RetroText = Color(0xFF33FF33)
val RetroTextFaded = Color(0xFF1B8E1B)
val RetroDigit = Color(0xFF0F200F)
val RetroOnDigit = Color(0xFF33FF33)
val RetroAction = Color(0xFF153315)
val RetroOnAction = Color(0xFF1B8E1B)
val RetroAccent = Color(0xFF33FF33)
val RetroOnAccent = Color(0xFF050B05)

// Lavender Dream (Sweet Pastel)
val LavenderBg = Color(0xFFFAF7FF)
val LavenderDisplayBg = Color(0xFFF2EBFC)
val LavenderText = Color(0xFF4A346B)
val LavenderTextFaded = Color(0xFF907EAC)
val LavenderDigit = Color(0xFFFFFFFF)
val LavenderOnDigit = Color(0xFF4A346B)
val LavenderAction = Color(0xFFE8DEFA)
val LavenderOnAction = Color(0xFF7B5CAB)
val LavenderAccent = Color(0xFFD473D4)
val LavenderOnAccent = Color(0xFFFFFFFF)
